services:
  twg_cli:
    container_name: twg4
    build:
      context: .
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      mynet:
        ipv4_address: 172.24.0.13
    tty: true
    restart: always

networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.24.0.0/24
        gateway: 172.24.0.1
